language: python
sudo: required
dist: trusty
group: deprecated-2017Q2
python:
  - "3.4"
install: "pip install -r requirements.txt"
addons:
  apt:
    packages:
     - python3-gi
script: python3 -m unittest
