language: python
sudo: required
dist: trusty
group: deprecated-2017Q2
python:
  - "3.5"
install: "pip install -r requirements.txt"
virtualenv:
  system_site_packages: true
addons:
  apt:
    packages:
     - python3-gi
     - gir1.2-gtk-3.0
     - gir1.2-glib-2.0
script: python3 -m unittest
